apiVersion: apps/v1
kind: Deployment
metadata:
  name: stc-poly-bridge-api-deployment
  labels:
    app: stc-poly-bridge-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stc-poly-bridge-api
  template:
    metadata:
      labels:
        app: stc-poly-bridge-api
    spec:
      containers:
      - name: stc-poly-bridge-api
        image: ghcr.io/starcoinorg/starcoin_poly_bridge_api:sha-14b6904
        ports:
        - containerPort: 8787
        env:
        - name: spring_profiles_active
          value: prod
        - name: FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS
          value: "true"
        - name: SPRING_SECURITY_HTPASSWD
          valueFrom:
            secretKeyRef:
              name: http-basic-auth
              key: auth
        - name: STARCOIN_MYSQL_URL
          value: "jdbc:mysql://starcoin-db-2.c0bz9kehdvnb.ap-northeast-1.rds.amazonaws.com:3306/stc_poly_bridge?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC"
        - name: STARCOIN_MYSQL_USER
          value: "starcoin"
        - name: STARCOIN_MYSQL_PWD
          valueFrom:
            secretKeyRef:
              name: mysql-pwd
              key: password
        - name: STARCOIN_NETWORK
          value: "main"
        - name: STARCOIN_JSON_RPC_URL
          value: "https://main-seed.starcoin.org"
#        - name: STARCOIN_SEEDS
#          value: "main4.seed.starcoin.org,main5.seed.starcoin.org"
        - name: STARCOIN_CHAIN_ID
          value: "1"
        - name: STARCOIN_ES_URL
          value: "search-starcoin-es2-47avtmhexhbg7qtynzebcnnu64.ap-northeast-1.es.amazonaws.com"
        - name: STARCOIN_ES_PROTOCOL
          value: "https"
        - name: STARCOIN_ES_PORT
          value: "443"
        - name: STARCOIN_ES_TXN_EVENT_IDX_PREFIX
          value: "main.0727"
        - name: STARCOIN_ES_USER
          value: elastic
        - name: STARCOIN_ES_PWD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-pw-elastic
              key: password

